### ISSUE TITLE
Failed to run swiftlint on ubuntu

### ISSUE THREAD

**Issue by dpliushchaiIOS** [ashfurrow/danger-ruby-swiftlint#177]
I use github action to run danger. It works fine on macOS but doesn't work on ubuntu.
![Screenshot 2022-02-03 at 23 09 33](https://user-images.githubusercontent.com/59007906/152421248-37fc35f3-5e53-4dd3-a31a-1be42f044345.png)

GitHub action .yml:
```
name: Danger
on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Setup gems
      run: |
        gem install bundler -v "2.2.21"
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec danger
```
