### ISSUE TITLE
Excluded files are being linted

### ISSUE THREAD

**Issue by noremac** [ashfurrow/danger-ruby-swiftlint#87]
I have a few directories set up to be excluded by SwiftLint in my `.swiftlint.yml` file. However, if these files change as part of a pull request, they are still linted by this plugin. Is there a way to disable this, or maybe this is a bug? I've been poking around in the readme and past issues, but could not find a mention of something like this. I apologize if I missed it!

I am using version`0.12.1` and my Dangerfile is set up like this:

``` ruby
swiftlint.binary_path = 'Pods/SwiftLint/swiftlint'
swiftlint.config_file = '.swiftlint.yml'
swiftlint.lint_files inline_mode: true
```

Thanks for the help!

**Comment by ashfurrow** [comment]
Hi there! Really good question, thanks for opening an issue. This is a bug in danger-ruby-swiftlint. I hit a similar problem in [danger-rubocop](https://github.com/ashfurrow/danger-rubocop) (SwiftLint but for Ruby). However, Rubocop has a handy flag that I used to get around the problem. That flag doesn't exist in SwiftLint, but I have [opened a feature request](https://github.com/realm/SwiftLint/issues/2051) to add one. If the request is turned down, we can still fix our bug here by parsing SwiftLint's config file itself and filtering out files. I'd strongly prefer to not do that, so I'm going to wait and see what they say first.

I'm afraid I can't think of any easy workaround on your end in the mean time. Sorry for the bug – thanks for understanding while we get this sorted out.

**Comment by noremac** [comment]
Thanks for the quick and thorough follow up! I'd be happy to help review or test anything that comes out of this.

**Comment by ashfurrow** [comment]
I've got an open PR to add this to SwiftLint: https://github.com/realm/SwiftLint/pull/2056

**Comment by omirho** [comment]
@ashfurrow Any update on this?

**Comment by ashfurrow** [comment]
The SwiftLint PR has not yet been merged, I’ve asked for an update from them.

**Comment by ashfurrow** [comment]
The PR has just been merged, we'll need to wait for a new version of SwiftLint to be made before moving forward.

**Comment by ashfurrow** [comment]
Still waiting for the next SwiftLint release, I'll check back next weekend.

**Comment by heidiproske** [comment]
@ashfurrow I've actually been using `danger-ruby-swiftlint` 0.12.1 quite happily across a number of projects and it has been working well for me (using the same `Dangerfile` setup as defined in this Issue). Specifically it has been adhering to exclusion request defined in my `swiftlint.yml` configuration: 

```
excluded: 
- Pods
```

However, I recently did a `bundle update` and my `danger-swiftlint` version was updated as below:
```
-    danger-swiftlint (0.12.1)
+    danger-swiftlint (0.16.0)
```

With this update, I'm now finding that I'm getting hundreds of lint warnings for files in my `Pods` folder 😨. 

As a test, I backdated two of my projects to use every `danger-ruby-swiftlint` version since `0.12.1` and reran my danger checks. My tests are showing that  that this bug was specifically introduced in `0.16.0`. i.e. if I run any older version `0.15.0`, `0.14.0`, `0.13.1` then it works well and I don't get the unwanted lint warnings for my exluded `Pods` folder. 

So I'm curious about this issue as I don't find the same result i.e. My excluded files are *not* being linted with `0.12.1` or any version after that except for with the latest version `0.16.0`.

As a short-term solution, I've gone ahead and pinned down my `danger-ruby-swiftlint` so that it will only use `0.15.0` but I'd obviously like to use the latest one. 

Curious to hear your thoughts  :)

**Comment by ashfurrow** [comment]
New SwiftLint has been released: https://github.com/realm/SwiftLint/releases/tag/0.25.1

I’ll get on to updating this plugin this week.

**Comment by AvdLee** [comment]
Yes @ashfurrow, you're right. @heidiproske the only thing introduced in 0.16 apart of extra logging is the support for environment variables (See [this pr](https://github.com/ashfurrow/danger-ruby-swiftlint/pull/99)). 

Do you use any environment variables in your config? It might be that they now get parsed correctly, which introduces the issues. 

It might also help to link your config file in this issue, so we can help you further.

**Comment by ashfurrow** [comment]
I've opened a PR to use the new `--force-excludes` flag here: https://github.com/ashfurrow/danger-ruby-swiftlint/pull/102 Any contributors up for reviewing it?

**Comment by ashfurrow** [comment]
This is fixed on `master`, I'll try to get a release done this week. Is someone available to point at the master branch in their Gemfile and test it out?

**Comment by noremac** [comment]
I just gave this a shot, here's what I did:

1. Updated my Gemfile to: `gem 'danger-swiftlint', :github => 'ashfurrow/danger-ruby-swiftlint'`
2. `bundle update danger-swiftlint`
3. Added a file named `blah.swift` with the following contents into my `Pods` folder (which is excluded in my `.swiftlint.yml`)
``` swift
let x: Int? = 0
 print(x!)
```
4. I then added that same code into a file that I would expect to be linted during a PR.

When the build finished, it reported both warnings instead of the just warning that I would expect from step 4.

Is there any other information you'd like me to grab to help diagnose?

**Comment by ashfurrow** [comment]
@noremac thank you – what does your SwiftLint config file look like? And could you confirm the SwiftLint version that CI is running?

**Comment by noremac** [comment]
Hey!

We are using SwiftLint `0.25.1` via a CocoaPod, and we are pointing at it like this in our Dangerfile:

```
swiftlint.binary_path = 'Pods/SwiftLint/swiftlint'
```

Here's my very lightly obfuscated `.swiftlint.yml`.

``` yml
disabled_rules: # rule identifiers to exclude from running
  - function_parameter_count
  - line_length
  - identifier_name
  - cyclomatic_complexity
  - nesting
  - large_tuple
  - unused_closure_parameter
  - for_where
  - notification_center_detachment
  - xctfail_message
  - fallthrough
  - superfluous_disable_command

opt_in_rules: # some rules are only opt-in
  - overridden_super_call
  - prohibited_super_call
  - force_unwrapping
  - empty_count
  - quick_discouraged_focused_test
  - sorted_first_last
  - override_in_extension
  - operator_usage_whitespace
  - operator_whitespace
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - joined_default_parameter
  - redundant_optional_initialization
  - unneeded_parentheses_in_closure_argument

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Application/Resources/CodeGen
  - Application/Utilities/UI/Web View Controller/ARIntegration/ARCommandErrorCode.swift
  - Frameworks/FusionGraph/Classes/graphql.swift
  - Frameworks/FusionContentLayer/Classes/Utilities/Swift Algorithm Club/Heap/Heap.swift
  - Frameworks/FusionContentLayer/Classes/Utilities/Swift Algorithm Club/Priority Queue/Priority Queue.swift
  - Frameworks/FusionContentLayer/Tests/HeapTests.swift
  - Frameworks/FusionContentLayer/Tests/PriorityQueueTests.swift
  - Vendor

type_body_length:
  - 700 #warning
  - 1000 #error

file_length:
  - 1000 #warning
  - 1200 #error

function_body_length:
  - 125 #warning
  - 200 #error

large_tuple:
  - 4 #warning
  - 5 #error

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 50

custom_rules:
  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning

  explicit_failure_calls:
    name: "Avoid asserting 'false'"
    regex: "((assert|precondition)\\(false)"
    message: "Use assertionFailure() or preconditionFailure() instead."
    severity: warning

  avoid_ipv4: # https://developer.apple.com/news/?id=05042016a
    name: "Avoid hard-coded IPV4 addresses"
    match_kinds: string
    regex: "([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])(\\.([01]?[0-9][0-9]?|2[0-4][0-9]|25[0-5])){3}"
    message: "Use IPV6-compatible addresses instead."
    severity: warning
```
